//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MarketOMaticEntities : DbContext
    {
        public MarketOMaticEntities()
            : base("name=MarketOMaticEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PinterestBoard> PinterestBoards { get; set; }
        public virtual DbSet<Site> Sites { get; set; }
        public virtual DbSet<SiteToken> SiteTokens { get; set; }
        public virtual DbSet<PinterestPinDetail> PinterestPinDetails { get; set; }
    }
}
