//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class PinterestBoard
    {
        public int PinterestBoardId { get; set; }
        public int SiteId { get; set; }
        public string BoardNumber { get; set; }
        public string BoardName { get; set; }
    
        public virtual Site Site { get; set; }
    }
}
