//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class PinterestPinDetail
    {
        public int PinDetailsId { get; set; }
        public string dataattribution { get; set; }
        public string datacreatorurl { get; set; }
        public string datacreatorfirst_name { get; set; }
        public string datacreatorlast_name { get; set; }
        public long datacreatorid { get; set; }
        public string dataurl { get; set; }
        public string datamediatype { get; set; }
        public string datacreated_at { get; set; }
        public long dataid { get; set; }
        public string datanote { get; set; }
        public string datacolor { get; set; }
        public string datalink { get; set; }
        public string databoardurl { get; set; }
        public long databoardid { get; set; }
        public string databoardname { get; set; }
        public string dataimageoriginalurl { get; set; }
        public int dataimageoriginalwidth { get; set; }
        public int dataimageoriginalheight { get; set; }
        public int datacountssaves { get; set; }
        public int datacountscomments { get; set; }
        public string dataoriginal_link { get; set; }
    }
}
